#include "pessoa.cpp"
#include "operario.cpp"
#include "vendedor.cpp"
#include "administrador.cpp"
#include <iostream>
#include <string>
#include <math.h>
using namespace std;

int main()
{
    string nome, rua, bairro;
    int CEP, numero, nSecao;
    float valorProducao, valorComissao, salarioBase, inss, valorVendas, comissao, ajudasDeCusto;
    long int CPF;
    int dia, mes, ano;
    float sal1, sal2, sal3, sal4, sal5, sal6, sal7, sal8, somaTotal;

    Operario op1;
    Operario op2;
    Operario op3;
    Operario op4;
    Operario op5;

    Vendedor v1;
    Vendedor v2;

    Administrador adm;

    cout << "Insira os dados do operario1 " << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    op1.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    op1.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    op1.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    op1.setdataNasc(dia, mes, ano);
    cout << endl << "Valor de Producao: ";
    cin >> valorProducao;
    op1.set_valorP(valorProducao);
    cout << endl << "Valor de Comissao: ";
    cin >> valorComissao;
    op1.set_valorC(valorComissao);
    sal1 = op1.calculaSalario();

    cout << "Insira os dados do operario2 " << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    op2.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    op2.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    op2.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    op2.setdataNasc(dia, mes, ano);
    cout << endl << "Valor de Producao: ";
    cin >> valorProducao;
    op2.set_valorP(valorProducao);
    cout << endl << "Valor de Comissao: ";
    cin >> valorComissao;
    op2.set_valorC(valorComissao);
    sal2 = op2.calculaSalario();

    cout << "Insira os dados do operario3 " << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    op3.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    op3.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    op3.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    op3.setdataNasc(dia, mes, ano);
    cout << endl << "Valor de Producao: ";
    cin >> valorProducao;
    op3.set_valorP(valorProducao);
    cout << endl << "Valor de Comissao: ";
    cin >> valorComissao;
    op3.set_valorC(valorComissao);
    sal3 = op3.calculaSalario();

    cout << "Insira os dados do operario4 " << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    op4.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    op4.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    op4.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    op4.setdataNasc(dia, mes, ano);
    cout << endl << "Valor de Producao: ";
    cin >> valorProducao;
    op4.set_valorP(valorProducao);
    cout << endl << "Valor de Comissao: ";
    cin >> valorComissao;
    op4.set_valorC(valorComissao);
    sal4 = op4.calculaSalario();

    cout << "Insira os dados do operario5 " << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    op5.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    op5.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    op5.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    op5.setdataNasc(dia, mes, ano);
    cout << endl << "Valor de Producao: ";
    cin >> valorProducao;
    op5.set_valorP(valorProducao);
    cout << endl << "Valor de Comissao: ";
    cin >> valorComissao;
    op5.set_valorC(valorComissao);
    sal5 = op5.calculaSalario();

    cout << "Insira os dados do vendedor1 " << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    v1.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    v1.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    v1.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    v1.setdataNasc(dia, mes, ano);
    cout << endl << "Numero Secao: ";
    cin >> nSecao;
    v1.set_numeroSecao(nSecao);
    cout << endl << "Salario Base: ";
    cin >> salarioBase;
    v1.set_salarioBase(salarioBase);
    cout << endl << "INSS: ";
    cin >> inss;
    v1.set_INSS(inss);
    cout << endl << "Valor de vendas: ";
    cin >> valorVendas;
    v1.setValorVendas(valorVendas);
    cout << endl << "Comissao: ";
    cin >> comissao;
    v1.setComissao(comissao);
    sal6 = v1.calculaSalario();

    cout << "Insira os dados do vendedor2" << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    v2.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    v2.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    v2.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    v2.setdataNasc(dia, mes, ano);
    cout << endl << "Numero Secao: ";
    cin >> nSecao;
    v2.set_numeroSecao(nSecao);
    cout << endl << "Salario Base: ";
    cin >> salarioBase;
    v2.set_salarioBase(salarioBase);
    cout << endl << "INSS: ";
    cin >> inss;
    v2.set_INSS(inss);
    cout << endl << "Valor de vendas: ";
    cin >> valorVendas;
    v2.setValorVendas(valorVendas);
    cout << endl << "Comissao: ";
    cin >> comissao;
    v2.setComissao(comissao);
    sal7 = v2.calculaSalario();

    cout << "Insira os dados do administrador" << endl;
    cout << endl << "Nome: ";
    cin >> nome;
    adm.setNome(nome);
    cout << endl << "CPF: ";
    cin >> CPF;
    adm.setCPF(CPF);
    cout << endl << "Rua :";
    cin >> rua;
    cout << endl << "Bairro: ";
    cin >> bairro;
    cout << endl << "Numero: ";
    cin >> numero;
    cout << endl << "CEP: ";
    cin >> CEP;
    adm.setEndereco(rua, numero, bairro, CEP);
    cout << endl << "Data de nascimento" << endl;
    cout << endl << "Dia: ";
    cin >> dia;
    cout << endl << "Mes: ";
    cin >> mes;
    cout << endl << "Ano: ";
    cin >> ano;
    adm.setdataNasc(dia, mes, ano);
    cout << endl << "Numero Secao: ";
    cin >> nSecao;
    adm.set_numeroSecao(nSecao);
    cout << endl << "Salario Base: ";
    cin >> salarioBase;
    adm.set_salarioBase(salarioBase);
    cout << endl << "INSS: ";
    cin >> inss;
    adm.set_INSS(inss);
    cout << endl << "Ajudas de Custo: ";
    cin >> ajudasDeCusto;
    adm.setAjuda(ajudasDeCusto);
    sal8 = adm.calcSalario();

    somaTotal = sal1 + sal2 + sal3 +sal4 + sal5 + sal6 + sal7 + sal8;
    cout << endl << "Soma de todo os salarios: " << somaTotal;

};
